
/**************************************************************
 *	
 *	icecream, 8 bit, 11025Hz,
 *	1 channel, 145408 bytes/channel
 *	Total Size: 1 * 145408 + 4 (header) = 145452 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\icecream.wav
 *	Time-stamp: Wed Apr 19 22:56:16 2017
 *	
 **************************************************************/

#ifndef __ICECREAMH__
#define __ICECREAMH__

#define ICECREAMFREQ 11025
#define ICECREAMLEN 145408

extern const unsigned char icecream[145408];

#endif /* __ICECREAMH__ */
