
/**************************************************************
 *	
 *	losesound, 8 bit, 11025Hz,
 *	1 channel, 34471 bytes/channel
 *	Total Size: 1 * 34471 + 4 (header) = 34515 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\losesound.wav
 *	Time-stamp: Wed Apr 19 23:16:37 2017
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 11025
#define LOSESOUNDLEN 34471

extern const unsigned char losesound[34471];

#endif /* __LOSESOUNDH__ */
