
/**************************************************************
 *	
 *	meow, 8 bit, 11025Hz,
 *	1 channel, 5956 bytes/channel
 *	Total Size: 1 * 5956 + 4 (header) = 6000 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\meow.wav
 *	Time-stamp: Sun Apr 02 18:01:21 2017
 *	
 **************************************************************/

#ifndef __MEOWH__
#define __MEOWH__

#define MEOWFREQ 11025
#define MEOWLEN 5956

extern const unsigned char meow[5956];

#endif /* __MEOWH__ */
