
/**************************************************************
 *	
 *	meow, 8 bit, 11025Hz,
 *	1 channel, 4874 bytes/channel
 *	Total Size: 1 * 4874 + 4 (header) = 4918 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\meow.wav
 *	Time-stamp: Tue Apr 04 00:56:04 2017
 *	
 **************************************************************/

#ifndef __MEOWH__
#define __MEOWH__

#define MEOWFREQ 11025
#define MEOWLEN 4874

extern const unsigned char meow[4874];

#endif /* __MEOWH__ */
