
/**************************************************************
 *	
 *	milkspill, 8 bit, 11025Hz,
 *	1 channel, 3547 bytes/channel
 *	Total Size: 1 * 3547 + 4 (header) = 3591 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\milkspill.wav
 *	Time-stamp: Wed Apr 19 22:22:09 2017
 *	
 **************************************************************/

#ifndef __MILKSPILLH__
#define __MILKSPILLH__

#define MILKSPILLFREQ 11025
#define MILKSPILLLEN 3547

extern const unsigned char milkspill[3547];

#endif /* __MILKSPILLH__ */
