
/**************************************************************
 *	
 *	pausesound, 8 bit, 11025Hz,
 *	1 channel, 80960 bytes/channel
 *	Total Size: 1 * 80960 + 4 (header) = 81004 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\pausesound.wav
 *	Time-stamp: Thu Apr 20 22:49:14 2017
 *	
 **************************************************************/

#ifndef __PAUSESOUNDH__
#define __PAUSESOUNDH__

#define PAUSESOUNDFREQ 11025
#define PAUSESOUNDLEN 80960

extern const unsigned char pausesound[80960];

#endif /* __PAUSESOUNDH__ */
