
/**************************************************************
 *	
 *	uke, 8 bit, 11025Hz,
 *	1 channel, 190728 bytes/channel
 *	Total Size: 1 * 190728 + 4 (header) = 190772 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\uke.wav
 *	Time-stamp: Thu Apr 20 22:41:52 2017
 *	
 **************************************************************/

#ifndef __UKEH__
#define __UKEH__

#define UKEFREQ 11025
#define UKELEN 190728

extern const unsigned char uke[190728];

#endif /* __UKEH__ */
