
/**************************************************************
 *	
 *	uke, 8 bit, 11025Hz,
 *	1 channel, 193313 bytes/channel
 *	Total Size: 1 * 193313 + 4 (header) = 193357 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\uke.wav
 *	Time-stamp: Sun Apr 02 19:04:28 2017
 *	
 **************************************************************/

#ifndef __UKEH__
#define __UKEH__

#define UKEFREQ 11025
#define UKELEN 193313

extern const unsigned char uke[193313];

#endif /* __UKEH__ */
