
/**************************************************************
 *	
 *	winsound, 8 bit, 11025Hz,
 *	1 channel, 98057 bytes/channel
 *	Total Size: 1 * 98057 + 4 (header) = 98101 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\winsound.wav
 *	Time-stamp: Wed Apr 19 23:50:49 2017
 *	
 **************************************************************/

#ifndef __WINSOUNDH__
#define __WINSOUNDH__

#define WINSOUNDFREQ 11025
#define WINSOUNDLEN 98057

extern const unsigned char winsound[98057];

#endif /* __WINSOUNDH__ */
