
/**************************************************************
 *	
 *	winsound, 8 bit, 11025Hz,
 *	1 channel, 97294 bytes/channel
 *	Total Size: 1 * 97294 + 4 (header) = 97338 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Marisa\Documents\GEORGIA TECH\SPRING 2017\CS 2261\FINAL PROJECT\MarisaHoenig_Final Project\winsound.wav
 *	Time-stamp: Wed Apr 19 23:39:52 2017
 *	
 **************************************************************/

#ifndef __WINSOUNDH__
#define __WINSOUNDH__

#define WINSOUNDFREQ 11025
#define WINSOUNDLEN 97294

extern const unsigned char winsound[97294];

#endif /* __WINSOUNDH__ */
